openapi: 3.0.3
info:
  description: REST API OpenAPI documentation for the User API
  title: users-api
  version: 1.0.0
servers:
- url: /
paths:
  /identity/users/{user_id}/lockout:
    delete:
      description: Destroy Lockout info from user.
      operationId: destroy_lockout_user
      parameters:
      - description: A unique integer value identifying the user.
        explode: false
        in: path
        name: user_id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "204":
          description: No response body
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "405":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultErrorResponse"
          description: Not Found
        "406":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultErrorResponse"
          description: Not Acceptable
        "429":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultErrorResponse"
          description: Too Many Requests
        "401":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultErrorResponse"
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultErrorResponse"
          description: Forbidden
      security:
      - TokenAuth: []
      - BearerAuth: []
      summary: Unlock user
      tags:
      - Users - Lockout
components:
  schemas:
    DefaultErrorResponse:
      additionalProperties: false
      example:
        detail: detail
      properties:
        detail:
          maxLength: 4096
          minLength: 1
          type: string
      title: DefaultErrorResponse
      type: object
  securitySchemes:
    BearerAuth:
      scheme: bearer
      type: http
    TokenAuth:
      description: Token-based authentication with required prefix "Token"
      in: header
      name: Authorization
      type: apiKey
